ALTER DATABASE analytics SET DATA_RETENTION_TIME_IN_DAYS = 5;
-- 5

SHOW PARAMETERS LIKE 'DATA_RETENTION_TIME_IN_DAYS' IN ACCOUNT;
-- 1 (default)

SHOW PARAMETERS LIKE 'DATA_RETENTION_TIME_IN_DAYS' IN DATABASE analytics;
-- 5

SHOW PARAMETERS LIKE 'DATA_RETENTION_TIME_IN_DAYS' IN SCHEMA analytics.staging;
-- 5
