GRANT USAGE ON SCHEMA DATA_WAREHOUSE.SALESFORCE_REP TO ROLE DEV_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA DATA_WAREHOUSE.SALESFORCE_REP TO ROLE DEV_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA DATA_WAREHOUSE.SALESFORCE_REP TO ROLE DEV_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DATA_WAREHOUSE.SALESFORCE TO ROLE DEV_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DATA_WAREHOUSE.SALESFORCE TO ROLE DEV_ROLE;
