-- Exposing to the other service account
GRANT USAGE ON DATABASE DATA_LAKE TO ROLE STARBURST_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE DATA_LAKE TO ROLE STARBURST_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE DATA_LAKE TO ROLE STARBURST_ROLE;
GRANT SELECT ON ALL VIEWS IN DATABASE DATA_LAKE TO ROLE STARBURST_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE DATA_LAKE TO ROLE STARBURST_ROLE;
GRANT SELECT ON FUTURE VIEWS IN DATABASE DATA_LAKE TO ROLE STARBURST_ROLE;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE DATA_LAKE TO ROLE STARBURST_ROLE;

-- Exposing to the users
GRANT USAGE ON SCHEMA DATA_WAREHOUSE.SALESFORCE_REP TO ROLE DEV_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA DATA_WAREHOUSE.SALESFORCE_REP TO ROLE DEV_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA DATA_WAREHOUSE.SALESFORCE_REP TO ROLE DEV_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DATA_WAREHOUSE.SALESFORCE TO ROLE DEV_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DATA_WAREHOUSE.SALESFORCE TO ROLE DEV_ROLE;






